#! /bin/sh

sxhkd &
~/.screenlayout/mylayout.sh & 
feh --bg-center ~/Pictures/Background/yosemite.jpg
pulseaudio &
pactl -- set-sink-volume 2 75%

xrandr --output DP-4 --primary --mode 3440x1440 --rotate normal --output DP-2.8 --mode 2560x1440 --rotate normal --right-of DP-4

bspc monitor %DP-4 -d I II III IV V 
bspc monitor %DP-2.8 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox     desktop='^2'
bspc rule -a '*:zathura' state=tiled
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

ckb-next&
~/dotfiles/bin/polylaunch &
